export const hostAndFramesData = [
  {
    id: 23,
    entity_name: "AEDEV",
    entity_description: "AE DEV System",
    serial_number: "78733F1",
    systemType: "host",
    type: "critical",
    msg: "Critical",
    val: 95,
  },
  {
    id: 10,
    entity_name: "DEMO03",
    entity_description: "Demo system 03",
    serial_number: "78EF2A3",
    systemType: "host",
    type: "critical",
    msg: "Critical",
    val: 90,
  },
  {
    id: 6,
    entity_name: "DEMO01",
    entity_description: "Demo system 01",
    serial_number: "78FD2A1",
    systemType: "host",
    type: "critical",
    msg: "Critical",
    val: 100,
  },
  {
    id: 1,
    entity_name: "AETEST",
    entity_description: "AE Test System",
    serial_number: "78733F1",
    systemType: "host",
    type: "warning",
    msg: "Warning",
    val: 20,
  },
  {
    id: 20,
    entity_name: "DAANW",
    entity_description: "DEALERS AA - NORTHWEST",
    serial_number: "2157B5W",
    systemType: "host",
    type: "warning",
    msg: "Warning",
    val: 75,
  },
  {
    id: 14,
    entity_name: "AEQA",
    entity_description: "AE QA System",
    serial_number: "78733F1",
    systemType: "frame",
    type: "good",
    msg: "Good",
    val: 40,
  },
  {
    id: 7,
    entity_name: "DEMO02",
    entity_description: "Demo system 02",
    serial_number: "78DF1B2",
    systemType: "host",
    type: "good",
    msg: "Good",
    val: 60,
  },
];
