import {
    getAllEvents,
    getAllSystems,
    getCPUData,
    getDiskSpaceUtilization,
    getNumberOfCors,
    getCPUMs,
    getGlobalMetrics,
    getSystemMetrics,
    getDiskArm,
    getReadWrite,
    getDiskOperations,
    getDiskResponse,
    getMachinePoolFaulting,
    getTotalFaultingRate,
    getTopPoolFaultingRate,
    getMemorySizeVsFaulting,
    getSpecificPoolFaulting,
    getResponseTime5250,
    getTotalTransactions,
    getCacheHitPercentage,
    getEthernetUtilization,
    getTopJobs,
    getCPUExecutiveReport,
    getDiskExecutiveReport,
    getMemoryExecutiveReport,
    getOtherExecutiveReport,
    getPoolsList
  } from "./apiService"; //move all to index

 const APIS = {
    getAllEvents,
    getAllSystems,
    getCPUData,
    getDiskSpaceUtilization,
    getNumberOfCors,
    getCPUMs,
    getGlobalMetrics,
    getSystemMetrics,
    getDiskArm,
    getReadWrite,
    getDiskOperations,
    getDiskResponse,
    getMachinePoolFaulting,
    getTotalFaultingRate,
    getTopPoolFaultingRate,
    getMemorySizeVsFaulting,
    getSpecificPoolFaulting,
    getResponseTime5250,
    getTotalTransactions,
    getCacheHitPercentage,
    getEthernetUtilization,
    getTopJobs,
    getCPUExecutiveReport,
    getDiskExecutiveReport,
    getMemoryExecutiveReport,
    getOtherExecutiveReport,
    getPoolsList
 }
 
 export default APIS;